apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: add-worker
  namespace: temporal-calc
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: add-worker
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: subtract-worker
  namespace: temporal-calc
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: subtract-worker
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: multiply-worker
  namespace: temporal-calc
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: multiply-worker
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: divide-worker
  namespace: temporal-calc
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: divide-worker
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: power-worker
  namespace: temporal-calc
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: power-worker
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
